version: "3"
services:
  php:
    image: php:apache
    build: './setup/php'
    depends_on:
      - mysql
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/www/html/:/var/www/html/
      - /usr/local/apache2/conf.d/docker.apache.conf:/usr/local/apache2/conf.d/docker.apache.conf
      - /usr/local/apache2/logs:/usr/local/apache2/logs

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    
  node:
    image: node
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./setup/nodejs/exp:/root/
    depends_on:
      - mysql
    command: node /root/dataHandleDocker.js serverIP mqttPort APIport mysql root password

  mysql:
    image: mysql
    restart: always
    volumes:
      - /var/lib/mysql/:/var/lib/mysql/
      - /etc/localtime:/etc/localtime
    ports:
      - "3306:3306"

  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
